runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  login: required

- url: /(.*)
  static_files: \1
  upload: .*
  secure: always
  login: required
