runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  login: required

- url: /(.*)
  static_files: dist/\1
  upload: dist/.*
  secure: always
  login: required